version: "3.10"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
      
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass

  pgAdmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=suhaib@alembicsoft.com
      - PGADMIN_DEFAULT_PASSWORD=alembic123
      - SCRIPT_NAME=/pgadmin4
    image: dpage/pgadmin4
    restart: always
    links:
      - database
    ports:
      - 8082:80